apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-home
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    repoURL: https://github.com/Accurate0/ingress-home.git
    path: kubernetes
    kustomize:
      images:
        - ingress-home=ghcr.io/accurate0/ingress-home:${ARGOCD_APP_REVISION}
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-home
operation:
  initiatedBy:
    username: github-actions
  sync:
    prune: true
    syncStrategy:
      hook: {}
